---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - runbook.runbook.io
  resources:
  - runbooks
  - runbooktemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runbook.runbook.io
  resources:
  - runbooks/finalizers
  - runbooktemplates/finalizers
  verbs:
  - update
- apiGroups:
  - runbook.runbook.io
  resources:
  - runbooks/status
  - runbooktemplates/status
  verbs:
  - get
  - patch
  - update
