title: Runbook Operator
description: A Kubernetes operator written in Go for managing operational runbooks and automating incident response procedures
github_repo: https://github.com/guibes/runbook-operator

# Jekyll settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
